require 'json'
require_relative '../RakefileUtils.rb'

desc "Build everything"
task :build => ["server.exe"] do
end

desc "Compile server.exe"
file 'server.exe' => ['server.cpp'] do
  compile_cpp("server.cpp")
end

desc "Clean everything"
task :clean do
  sh "rm -rf *.exe"
end

desc "Try it"
task :try => [:build] do
  sh "./server.exe"
end

task :default => :build
